ims/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from core.views import *

urlpatterns = [
    # admin
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret-panel/', admin.site.urls),
    # auth
    path('accounts/', include('allauth.urls')),
    # help
    path('contact/', contact, name='contact'),
    # home & user management
    path('', HomeView.as_view(), name='home'),
    path('users/', UserManagement.as_view(), name='user'),
    path('user/<username>/', EditUserManagent.as_view(), name='user-edit'),
    # Suppliers url
    path('purchase/suppliers/', SupplierModalCreate.as_view(), name='supplier-modal'),
    path('suppliers/', SupplierCreateView.as_view(), name='supplier'),
    path('suppliers/<int:pk>/', SupplierUpdateView.as_view(), name='supplier-update'),
    path('suppliers/delete/<int:pk>/',
         SupplierDeleteView.as_view(), name='supplier-delete'),
    # Purchases urls
    path('purchases/', PurchaseProductCreateView.as_view(), name='purchase'),
    path('purchases/report', PurchaseProductReportView.as_view(),
         name='purchase-report'),
    path('purchase/<int:pk>/', PurchaseProductUpdateView.as_view(),
         name='purchase-update'),
    path('purchase/delete/<int:pk>/',
         PurchaseProductDeleteView.as_view(), name='purchase-delete'),
    # stocks urls
    path('stocks/', StockCreateView.as_view(), name='stock'),
    path('stocks/<int:pk>/', StockUpdateView.as_view(), name='stock-update'),
    path('stocks/delete/<int:pk>/', StockDeleteView.as_view(), name='stock-delete'),
    # sells urls
    path('sells/list/', SellsListView.as_view(), name='sell-list'),
    path('sells/', SellProductCreateView.as_view(), name='sell-create'),
    path('sells/<int:pk>/', SellProductUpdateView.as_view(), name='sell-update'),
    path('sells/product/<int:pk>/', SellProductByID.as_view(),
         name='sell-product-by-id'),
    path('sells/delete/<int:pk>/',
         SellProductDeleteView.as_view(), name='sell-delete'),
    # sells report urls
    path('sells/report/', SellProductReportView.as_view(), name='sell-report'),
    path('sells/report/<download>',
         SellProductReportView.as_view(), name='sell-report-pdf'),
    path('sells/invoice/<int:pk>', sell_invoice, name='sell-invoice'),
    # charts urls
    path('charts/', ChartView.as_view(), name='charts'),
    path('sells/chart/', SellReportView.as_view(), name='report'),
    # search endpoints
    path('sells/search', csrf_exempt(SellProductSearch.as_view()), name="sells-search"),
    path('purchases/search', csrf_exempt(PurchaseProductSearch.as_view()),
         name="purchases-search"),
    path('supplier/search', csrf_exempt(SupplierSearch.as_view()),
         name="supplier-search"),
]

admin.site.site_header = 'Sales Manager Panel'
admin.site.index_title = 'Sales Manager'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse

from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.sites.models import Site

from datetime import datetime


class LoginExpire(models.Model):
    title = models.CharField(max_length=100)
    message = models.CharField(max_length=100)
    expire_date = models.DateField()

    def __str__(self):
        return self.title


class Office(models.Model):
    name = models.CharField(max_length=30, unique=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=11)
    address = models.TextField()
    status = models.BooleanField(default=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    office = models.ForeignKey(Office, on_delete=models.SET_NULL, null=True)
    email = models.EmailField(_('email address'), blank=True, unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateField(_('date joined'), default=timezone.now)

    def __str__(self):
        return self.username


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(max_length=254)
    is_active = models.BooleanField(default=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added', '-id']

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse("supplier-update", kwargs={"pk": self.pk})
    
    def get_delete_url(self):
        return reverse("supplier-delete", kwargs={"pk": self.pk})
    

class PurchaseProduct(models.Model):
    supplier = models.ForeignKey(Supplier, blank=True, null=True, on_delete=models.SET_NULL)
    
    product_name = models.CharField(max_length=30, default='Wheat')
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField()
    chalan_number = models.CharField(max_length=30, blank=True, null=True)

    date_added = models.DateField(default=datetime.today)
    date_updated = models.DateField(auto_now_add=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-date_added', '-id']

    def __str__(self):
        return self.product_name

    def get_update_url(self):
        return reverse("purchase-update", kwargs={"pk": self.pk})
    
    def get_delete_url(self):
        return reverse("purchase-delete", kwargs={"pk": self.pk})

    @property
    def total_purchase_price(self):
        return (self.quantity * self.price)


class Stock(models.Model):
    product_name = models.CharField(max_length=30)
    quantity = models.PositiveIntegerField()
    # sell_price = models.DecimalField(blank=True, null=True, max_digits=8, decimal_places=2)

    date_added = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-date_updated', '-id']

    def __str__(self):
        return self.product_name

    def get_update_url(self):
        return reverse("stock-update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("stock-delete", kwargs={"pk": self.pk})


class SellProduct(models.Model):
    SACK_CHOICES = (
        (5, '5 kg'),
        (35, '35 kg'),
        (37, '37 kg'),
        (50, '50 kg'),
        (55, '55 kg'),
        (60, '60 kg')
    )

    product_name = models.ForeignKey(Stock, null=True, on_delete=models.SET_NULL)
    product_label = models.CharField(max_length=254, blank=True, null=True)
    sack = models.IntegerField(choices=SACK_CHOICES)
    quantity = models.PositiveIntegerField()
    sell_price = models.DecimalField(max_digits=8, decimal_places=2)
    customer_name = models.CharField(max_length=30)
    token_number = models.CharField(max_length=11)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2)

    date_added = models.DateField(default=datetime.today)
    date_updated = models.DateField(auto_now_add=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-date_added', '-id']

    def __str__(self):
        if self.product_name:
            return str(self.product_name)
        return self.product_label

    def save(self, *args, **kwargs):
        self.product_label = str(self.product_name)
        super(SellProduct, self).save(*args, **kwargs)

    def get_update_url(self):
        return reverse("sell-update", kwargs={"pk": self.pk})
    
    def get_delete_url(self):
        return reverse("sell-delete", kwargs={"pk": self.pk})

    @property
    def is_paid(self):
        if self.paid_amount == 0:
            return True
        else:
            return False

    @property
    def get_total_amount(self):
        return (self.sell_price * self.quantity)

    @property
    def get_due_amount(self):
        return (self.get_total_amount - self.paid_amount)

templates/charts.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}| Charts{% endblock title %}


{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Stock Chart</h6>
                    </div>
                    <div class="card-body">
                        <canvas id="myBarChart" height="400"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

{% block script %}
<script>

    /*var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [
                {% for product in stocks %}
                    '{{product.product_name}}',
                {% endfor %}
            ],
            datasets: [{
                label: 'Products',
                data: [
                    {% for product in stocks %}
                    {{product.quantity}},
                    {% endfor %}
                ],
                backgroundColor: 'rgb(16, 80, 173)',

                
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    }); */




    // Set new default font family and font color to mimic Bootstrap's default styling
    Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
    Chart.defaults.global.defaultFontColor = '#858796';

    function number_format(number, decimals, dec_point, thousands_sep) {
    // *     example: number_format(1234.56, 2, ',', ' ');
    // *     return: '1 234,56'
    number = (number + '').replace(',', '').replace(' ', '');
    var n = !isFinite(+number) ? 0 : +number,
        prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
        sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
        dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
        s = '',
        toFixedFix = function(n, prec) {
        var k = Math.pow(10, prec);
        return '' + Math.round(n * k) / k;
        };
    // Fix for IE parseFloat(0.55).toFixed(0) = 0;
    s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
    if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
    }
    if ((s[1] || '').length < prec) {
        s[1] = s[1] || '';
        s[1] += new Array(prec - s[1].length + 1).join('0');
    }
    return s.join(dec);
    }

    // Bar Chart Example
    var ctx = document.getElementById("myBarChart");
    var myBarChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [
            {% for product in stocks %}
                '{{product.product_name}}',
            {% endfor %}
        ],
        datasets: [{
        label: "Available",
        backgroundColor: "#4e73df",
        hoverBackgroundColor: "#2e59d9",
        borderColor: "#4e73df",
        data: [
            {% for product in stocks %}
            {{product.quantity}},
            {% endfor %}
        ],
        }],
    },
    options: {
        maintainAspectRatio: false,
        layout: {
        padding: {
            left: 10,
            right: 25,
            top: 25,
            bottom: 0
        }
        },
        scales: {
        xAxes: [{
            time: {
            unit: 'month'
            },
            gridLines: {
            display: false,
            drawBorder: false
            },
            ticks: {
            maxTicksLimit: 6
            },
            maxBarThickness: 25,
        }],
        yAxes: [{
            ticks: {
            min: 0,
            //max: 15000,
            maxTicksLimit: 5,
            padding: 10,
            // Include a dollar sign in the ticks
            callback: function(value, index, values) {
                return '' + number_format(value);
            }
            },
            gridLines: {
            color: "rgb(234, 236, 244)",
            zeroLineColor: "rgb(234, 236, 244)",
            drawBorder: false,
            borderDash: [2],
            zeroLineBorderDash: [2]
            }
        }],
        },
        legend: {
        display: false
        },
        tooltips: {
        titleMarginBottom: 10,
        titleFontColor: '#6e707e',
        titleFontSize: 14,
        backgroundColor: "rgb(255,255,255)",
        bodyFontColor: "#858796",
        borderColor: '#dddfeb',
        borderWidth: 1,
        xPadding: 15,
        yPadding: 15,
        displayColors: false,
        caretPadding: 10,
        callbacks: {
            label: function(tooltipItem, chart) {
            var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
            return datasetLabel + ': ' + number_format(tooltipItem.yLabel);
            }
        }
        },
    }
    });

</script>
{% endblock script %}

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}| {{ title }}{% endblock title %}


{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card shadow">
                    <div class="card-header">
                        <strong class="text-primary">Developer</strong>
                    </div>
                    <div class="card-body">
                        <h4><a href="#" target="_blank">Blueskyocean</a></h4>
                        <a href="mailto:miclee0312@gmail.com">
                            <i class="fas fa-envelope text-secondary mr-2"></i> 
                            miclee0312@gmail.com 
                        </a>
                        <br>
                        <i class="fab fa-whatsapp-square text-success mr-3"></i>01718-925923
                        <br>
                        <i class="fas fa-phone text-info mr-3"></i>01718-925923
                        <br>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card mb-4 shadow">
                    <div class="card-header">
                        <strong class="text-primary">Email Us</strong>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="buttons-right">
                                <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div> {% endcomment %}
    </div>
{% endblock body %}

templates/purchase_report.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}| {{ title|title }}{% endblock title %}

{% block body %}

<div class="container-fluid">

    <!-- Content Row -->

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ title|title }}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <form action="" method="GET">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="id_date_added">Date</label>
                            <input class="form-control" type="date" name="date_added" id="id_date_added">
                        </div>
                        <div class="col-md-4">
                            <label for="id_start_date">Start Date</label>
                            <input class="form-control" type="date" name="start_date" id="id_start_date">
                        </div>
                        <div class="col-md-4">
                            <label for="id_end_date">End Date</label>
                            <input class="form-control" type="date" name="end_date" id="id_end_date">
                        </div>
                    </div>
                    <div class="buttons-right">
                        <button type="submit" class="btn btn-sm btn-primary mt-1"><i class="fa fa-filter"></i> Filter</button>
                        <a href="{% url 'sell-report' %}" class="btn btn-sm btn-secondary mt-1">Cancel</a>
                    </div>
                </form>
                
                <div class="report-parameter mt-5">
                    <div class="card">
                        <div class="card-header text-primary">
                            <h6 class="m-0 font-weight-bold text-primary">Report Parameters</h6>
                        </div>
                        <div class="card-body">
                            <div class="filteredBy">
                            {% if searched_for %}
                                {% for key, value in searched_for.items %}
                                    <span class="mr-3"><b>{{key|capfirst}}: </b>{{value}}</span> 
                                {% endfor %}
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                {% comment %} <br> {% endcomment %}
                <br>
                <button id="downloadReportPDF" class="btn btn-sm btn-primary buttons-right d-inline">Download PDF <i class="fa fa-cloud-download-alt"></i></button>
                <br>
                <br>
                <table class="table table-bordered" id="reportDataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total</th>
                            <th>Supplier</th>
                            <th>Chalan</th>
                            <th>Date</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for obj in filter %}
                        <tr>
                            <td>{{ obj.product_name }}</td>
                            <td>{{ obj.quantity }}</td>
                            <td>{{ obj.price }}</td>
                            <td>{{ obj.total_purchase_price }}</td>
                            <td>{{ obj.supplier }}</td>
                            <td>{{ obj.chalan_number }}</td>
                            <td>{{ obj.date_added|date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>

                    <thead>
                        <tr>
                            <th colspan="3" class="text-right">Grand Total =</th>
                            <th>{{ grand_total_price }}</th>
                            <th colspan="4"></th>
                        </tr>
                    </thead>
                    
                </table>

            </div>
        </div>
    </div>
</div>

{% endblock body %}

{% block script %}
    <script src="{% static 'js/download-report.js' %}"></script>
{% endblock script %}

templates/sell_report.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}| {{ title|title }}{% endblock title %}

{% block body %}

<div class="container-fluid">

    <!-- Content Row -->

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ title|title }}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <form action="" method="GET">
                    <div class="row">
                        <div class="col-md-4">
                            {% comment %} {{filter.form.customer_name|as_crispy_field}} {% endcomment %}
                            <label for="id_customer_name">Customer Name</label>
                            <input class="form-control" type="text" name="customer_name" id="id_customer_name">
                        </div>
                        <div class="col-md-4">
                            {% comment %} {{filter.form.token_number|as_crispy_field}} {% endcomment %}
                            <label for="id_token_number">Token</label>
                            <input class="form-control" type="text" name="token_number" id="id_token_number">
                        </div>
                        <div class="col-md-4">
                            {% comment %} {{sellproductFilter.form.product_name|as_crispy_field}} {% endcomment %}
                            <label for="id_product_name">Product Name</label>
                            <input class="form-control" type="text" name="product_name" id="id_product_name">
                        </div>
                        <div class="col-md-4">
                            <label for="id_date_added">Date</label>
                            <input class="form-control" type="date" name="date_added" id="id_date_added">
                        </div>
                        <div class="col-md-4">
                            <label for="id_start_date">Start Date</label>
                            <input class="form-control" type="date" name="start_date" id="id_start_date">
                        </div>
                        <div class="col-md-4">
                            <label for="id_end_date">End Date</label>
                            <input class="form-control" type="date" name="end_date" id="id_end_date">
                        </div>
                    </div>
                    <div class="buttons-right">
                        <button type="submit" class="btn btn-sm btn-primary mt-1"><i class="fa fa-filter"></i> Filter</button>
                        <a href="{% url 'sell-report' %}" class="btn btn-sm btn-secondary mt-1">Cancel</a>
                    </div>
                </form>
                
                <div class="report-parameter mt-5">
                    <div class="card">
                        <div class="card-header text-primary">
                            <h6 class="m-0 font-weight-bold text-primary">Report Parameters</h6>
                        </div>
                        <div class="card-body">
                            <div class="filteredBy">
                            {% if searched_for %}
                                {% for key, value in searched_for.items %}
                                    <span class="mr-3"><b>{{key|capfirst}}: </b>{{value}}</span> 
                                {% endfor %}
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="report-summary mt-3">
                    <div class="card">
                        <div class="card-header text-primary">
                            <h6 class="m-0 font-weight-bold text-primary">Report Summary</h6>
                        </div>
                        <div class="card-body">
                            <div class="row d-flex justify-content-between">
                                <div class="col-lg-4">
                                    <table width="100%">
                                        <tbody>
                                            <tr>
                                                <th>Total Sale</th>
                                                <td>{{ filter.count }}</td>
                                            </tr>
                                            <tr>
                                                <th>Total Sale Price</th>
                                                <td>{{ total_sell }}</td>
                                            </tr>
                                            <tr>
                                                <th>Total Paid</th>
                                                <td>{{ total_paid }}</td>
                                            </tr>
                                            <tr>
                                                <th>Total Due</th>
                                                <td>{{ total_due }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-lg-7 ">
                                    <table class="table table-bordered" width="100%">
                                        <tbody>
                                            <tr>
                                                <th>Product Sack</th>
                                                <td>5kg</td>
                                                <td>35kg</td>
                                                <td>37kg</td>
                                                <td>50kg</td>
                                                <td>55kg</td>
                                                <td>60kg</td>
                                            </tr>
                                            <tr>
                                                <th>Quantity</th>
                                                {% for key, value in sack_count.items %}
                                                <td> {{value}}</td>
                                                {% endfor %}
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% comment %} <br> {% endcomment %}
                <br>
                <button id="downloadReportPDF" class="btn btn-sm btn-primary buttons-right d-inline">Download PDF <i class="fa fa-cloud-download-alt"></i></button>
                <br>
                <br>
                <table class="table table-bordered" id="reportDataTable" width="100%" cellspacing="0" style="font-size: 14px;">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Sack</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total</th>
                            <th>Paid</th>
                            <th>Due</th>
                            <th>Customer</th>
                            <th>Token</th>
                            <th>Date</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for obj in filter %}
                        <tr>
                            <td>{{ obj.product_name }}</td>
                            <td>{{ obj.sack }} kg</td>
                            <td>{{ obj.quantity }}</td>
                            <td>{{ obj.sell_price }}</td>
                            <td>{{ obj.get_total_amount }}</td>
                            <td>{{ obj.paid_amount }}</td>
                            <td>{{ obj.get_due_amount }}</td>
                            <td>{{ obj.customer_name }}</td>
                            <td>{{ obj.token_number }}</td>
                            <td>{{ obj.date_added|date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>

                    <thead>
                        <tr>
                            <th colspan="4" class="text-right">Grand Total =</th>
                            <th>{{ total_sell }}</th>
                            <th>{{ total_paid }}</th>
                            <th>{{ total_due }}</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    
                </table>

            </div>
        </div>
    </div>
</div>

{% endblock body %}

{% block script %}
    <script src="{% static 'js/download-report.js' %}"></script>
{% endblock script %}